# Welcome to the standard bot config file.
# In this file you can manage the general bot behavior.

console:
  level: info # Valid levels: trace, debug, info, warn

bot:
  prefix: "!" # still works but slash commands are present
  prefix_enabled: true
  rich_presence_enabled: true
  rich_presence: "reactions since 2019"
  rich_presence_type: "watching" # Valid types: playing, watching, listening to, streaming
  bot_status: "dnd" # Valid types: online, dnd, idle, invisible

reaction_logging:
  enabled: false
  log_guild: 123456789987654321
  log_channel: 123456789987654321

token:
  # Environment variable token, do not enable unless you know what you are doing.
  token_env_enabled: true
  token_env: "DISCORD_TOKEN"

  # If not token_env_enabled, provide a bot token here.
  token: "XXXYOURBOTTOKENHEREXXX"

leveling:
  enabled: false
  max_top: 25
  guild: 123456789987654321
  notification_channel: 123456789987654321
  roles:
    # level: roleid
    2: 123456789987654321

# Format:
# reaction_roles:
#   messageId:
#     - [emoji, roleId]
#     - [emoji, roleId]
#   messageId:
#     - [emoji, roleId]
reaction_roles:
  123456789987654321:
    - ["😃", 123456789987654321]
