[package]
name = "bot"
version = "0.1.0"
readme.workspace = true
description.workspace = true
authors.workspace = true
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
tokio.workspace = true
tracing.workspace = true

poise = "0.7.0"
serde = { version = "1.0.229", features = ["derive"] }
serde_yaml = "0.9.34"
rand = "0.10.3"
sqlx = { version = "0.9.0", features = ["runtime-tokio", "sqlite"] }
futures = "0.3.34"
chrono = "0.4.45"
itertools = "0.15.0"
