---
name: Rust Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    container:
      image: arthurdw/rust-ci:latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Tests with cargo-nextest
        run: cargo nextest run --all
